version: "3"
services:
  web:
    build:
      context: ../.
      dockerfile: development/Dockerfile-dev
    container_name: "metadata_submitter_backend_dev"
    ports:
      - 5430:5430
    depends_on:
      - database
    restart: on-failure
    environment:
      - "MONGODB_HOST=database:27017"
  database:
    image: "mongo"
    container_name: "metadata_submitter_database_dev"
    restart: on-failure
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=admin"
    volumes:
      - data:/data/db
    expose:
      - 27017

volumes:
  data: 
