from typing import Tuple

import pytest

from metadata_backend.api.exceptions import UserException
from metadata_backend.api.models.rems import (
    Organizations,
    RemsLicense,
    RemsLicenseLocalization,
    RemsOrganization,
    RemsWorkflow,
    RemsWorkflowDetails,
)
from metadata_backend.api.models.submission import Rems
from metadata_backend.api.services.rems import (
    RemsLicenseProvider,
    RemsOrganisationsService,
    generate_rems_license_id,
    resolve_rems_license_ids,
)

ORGANISATION_ID = "Organisation id"
ORGANISATION_NAME = "Organisation name"
LICENSE_ID = 1
LICENSE_TITLE = "License title"
LICENSE_TEXT_CONTENT = "License text content"
LICENCE_ATTACHEMENT_ID = "License attachment id"
WORKFLOW_ID = 1
WORKFLOW_TITLE = "Workflow title"


def create_workflow_and_license() -> Tuple[list[RemsWorkflow], list[RemsLicense]]:
    rems_organization = RemsOrganization(
        id=ORGANISATION_ID, name={"en": ORGANISATION_NAME}, short_name={"en": "Test Short Name"}
    )
    rems_license_localization = RemsLicenseLocalization(
        title=LICENSE_TITLE,
        textcontent=LICENSE_TEXT_CONTENT,
    )
    rems_license = RemsLicense(
        id=LICENSE_ID,
        licensetype="Test Licence Type",
        localizations={"en": rems_license_localization},
        organization=rems_organization,
    )
    rems_workflow = RemsWorkflow(
        id=WORKFLOW_ID,
        title=WORKFLOW_TITLE,
        organization=rems_organization,
        workflow=RemsWorkflowDetails(
            type="default",
            licenses=[rems_license],
        ),
        archived=False,
        enabled=True,
    )

    return [rems_workflow], [rems_license]


def assert_organisation(organisations: Organizations) -> None:
    assert len(organisations) == 1

    # Check organisation.
    organisation = organisations[0]
    assert organisation is not None
    assert organisation.id == ORGANISATION_ID
    assert organisation.name == ORGANISATION_NAME

    # Check licenses.
    assert len(organisation.licenses) == 1
    rems_license = organisation.licenses[0]
    assert rems_license.id == LICENSE_ID
    assert rems_license.title == LICENSE_TITLE
    assert rems_license.textcontent == LICENSE_TEXT_CONTENT

    # Check workflows.
    assert len(organisation.workflows) == 1
    workflow = organisation.workflows[0]
    assert workflow.id == WORKFLOW_ID
    assert workflow.title == WORKFLOW_TITLE
    assert len(workflow.licenses) == 1
    assert workflow.licenses[0] == rems_license


async def test_get_organizations():
    rems_workflows, rems_licenses = create_workflow_and_license()
    organisations = await RemsOrganisationsService.get_organisations(rems_workflows, rems_licenses)
    assert_organisation(list(organisations.values()))


PROVIDED_LICENSE_ID = 1
PROVIDED_LICENSE_LOCALIZATIONS = {"en": RemsLicenseLocalization(title="Terms", textcontent="You agree.")}
SUBMISSION_ID = "submission-1"


class _MockRemsService:
    """REMS service methods used by license resolution."""

    def __init__(self, *, unknown_license: bool = False) -> None:
        self.checked_license_ids: list[int] = []
        self.generated_localizations: list[dict[str, RemsLicenseLocalization]] = []
        self._unknown_license = unknown_license

    async def get_license(self, _: str, license_id: int) -> None:
        if self._unknown_license:
            raise UserException(f"Unknown REMS license '{license_id}'")
        self.checked_license_ids.append(license_id)

    async def get_or_create_license(self, _: str, localizations: dict[str, RemsLicenseLocalization]) -> int:
        self.generated_localizations.append(localizations)
        return PROVIDED_LICENSE_ID


class _MockRemsLicenseProvider(RemsLicenseProvider):
    """REMS license provider methods used by license resolution."""

    def __init__(self, localizations: dict[str, RemsLicenseLocalization] | None) -> None:
        self._localizations = localizations

    async def get_license(self, _: str) -> dict[str, RemsLicenseLocalization] | None:
        return self._localizations


@pytest.mark.parametrize(
    "given, provided, expected_resolved, expected_checked, expected_generated",
    [
        # Given licenses are used and every one of them is checked. No licenses are generated.
        ([1, 2], PROVIDED_LICENSE_LOCALIZATIONS, [1, 2], [1, 2], []),
        # No licenses given, so none are checked. License generated by the provider.
        (None, PROVIDED_LICENSE_LOCALIZATIONS, [PROVIDED_LICENSE_ID], [], [PROVIDED_LICENSE_LOCALIZATIONS]),
        # No licenses given or generated by the provider.
        (None, None, [], [], []),
    ],
)
async def test_resolve_rems_license_ids(given, provided, expected_resolved, expected_checked, expected_generated):
    rems_service = _MockRemsService()
    provider = _MockRemsLicenseProvider(provided)
    rems = Rems(workflowId=1, licenses=given)

    license_ids = await resolve_rems_license_ids(rems_service, provider, rems, SUBMISSION_ID, ORGANISATION_ID)

    assert license_ids == expected_resolved
    assert rems_service.checked_license_ids == expected_checked
    assert rems_service.generated_localizations == expected_generated


async def test_resolve_rems_license_ids_unknown_license():
    rems_service = _MockRemsService(unknown_license=True)
    rems = Rems(workflowId=1, licenses=[404])

    with pytest.raises(UserException, match="Unknown REMS license"):
        await resolve_rems_license_ids(rems_service, None, rems, SUBMISSION_ID, ORGANISATION_ID)


async def test_generate_rems_license_id_no_provider():
    assert await generate_rems_license_id(_MockRemsService(), None, SUBMISSION_ID, ORGANISATION_ID) is None
