version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    labels:
      - "pip dependencies"
    target-branch: "develop"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    labels:
      - "github actions"
    target-branch: "develop"
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    labels:
      - "docker dependencies"
    target-branch: "develop"
    open-pull-requests-limit: 10
