version: "3"
services:
  database:
    image: "mongo"
    container_name: "metadata_db_database"
    restart: on-failure
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=admin"
      - "MONGODB_HOST=localhost:27017"
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

volumes:
  data: 
