version: "3"
services:
  database:
    image: "mongo"
    container_name: "metadata_db_database"
    restart: on-failure
    env_file: 
      - ../../.env
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

volumes:
  data: 
