stages:
  - test
  - build
  - upload
  - release

# Release process
include:
  - project: "sds-dev/releases"
    ref: main
    file: "releases.yml"

# Make all jobs interruptible by default
default:
  interruptible: true


#
# Test stage
#
1-verify:
  stage: test
  tags:
    - sds-test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  image: sds-docker.artifactory.ci.csc.fi/sds/sdd-common-ci:1659d8af0e3757081843f2a191cd804de97e94e4
  script:
    # Install uv to /uv and tox uv tool called by pre-commit to /root/.local/bin.
    - curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="/uv" sh
    - export PATH="/uv:/root/.local/bin:$PATH"
    - uv tool install tox --with tox-uv
    - SKIP=test uv tool run pre-commit run --all-files -c .pre-commit-config.yaml --show-diff-on-failure --color never

2-unit-test:
  stage: test
  needs:
    - job: 1-verify
  tags:
    - sds-test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "metadata-backend/**/*"
          - "tests/**/*"
          - ".gitlab-ci.yml"
          - ".pre-commit-config.yaml"
          - "pyproject.toml"
          - "tox.ini"
          - "uv.lock"
        compare_to: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  image: sds-docker.artifactory.ci.csc.fi/sds/sdd-common-ci:1659d8af0e3757081843f2a191cd804de97e94e4
  script:
    # Install uv to /uv and tox uv tool called by pre-commit to /root/.local/bin.
    - curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="/uv" sh
    - export PATH="/uv:/root/.local/bin:$PATH"
    - uv tool install tox --with tox-uv
    - uv tool run pre-commit run test --all-files -c .pre-commit-config.yaml --show-diff-on-failure --color never
    - uv tool run coverage report --precision=1
  coverage: '/TOTAL.*?([\d.]+%)/'

3-integration-test:
  stage: test
  needs:
    - job: 1-verify
  tags:
    - sds-test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "dockerfiles/**/*"
          - "metadata-backend/**/*"
          - "tests/**/*"
          - ".gitlab-ci.yml"
          - "docker-compose.yml"
          - "Makefile"
          - "pyproject.toml"
          - "uv.lock"
        compare_to: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  image: sds-docker.artifactory.ci.csc.fi/sds/sdd-common-ci:1659d8af0e3757081843f2a191cd804de97e94e4
  variables:
    COMPOSE_PROJECT_NAME: $CI_JOB_ID
    VAULT_ADDR: $VAULT_TEST_ADDR
    VAULT_ROLE_ID: $VAULT_ROLE_ID
    VAULT_SECRET_ID: $VAULT_SECRET_ID
  script:
    # Get secrets from Vault for testing
    - make get_ci_env
    # Run integration tests with integration-test-runner service in docker-compose
    - docker compose -f docker-compose.yml --env-file tests/integration/.env --profile ci run --build integration-test-runner || export TEST_FAILED=1
    - |
      if [ "$TEST_FAILED" = "1" ]; then
        echo "Tests failed, printing all docker-compose logs:"
        docker compose --env-file tests/integration/.env --profile ci logs
        exit 1
      fi
  after_script:
    # Shut down containers after the tests finish.
    - docker compose --profile ci down -v --remove-orphans


#
# Build, Scan and Upload.
#
# I'd like to split this into two stages "build" and "upload", but that fails as the image wouldn't
# be available to both stages - I can't use "docker save" because the size of the generated docker
# image exceeds our limit.
#
1-build-image:
  stage: build
  tags:
    - sds-build
  needs: []
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: true
  script:
    - |
      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
        export IMAGE_TAG="$(echo ${ENVIRONMENT:-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} | tr '/' '-')"
      elif [ "$CI_COMMIT_TAG" ]; then
        export IMAGE_TAG="$CI_COMMIT_TAG"
      else
        export IMAGE_TAG="$CI_DEFAULT_BRANCH"
      fi
    - echo "Building image sd-submit-api:${IMAGE_TAG}"
    - docker buildx build -t "$ARTIFACTORY_SERVER/sds/sd-submit-api:${IMAGE_TAG}" -f dockerfiles/Dockerfile .
    - docker save "$ARTIFACTORY_SERVER/sds/sd-submit-api:${IMAGE_TAG}" | gzip > image.tar.gz
  artifacts:
    paths:
      - image.tar.gz
    expire_in: 1 day

2-scan-image:
  stage: build
  needs:
    - job: 1-build-image
      artifacts: true
  tags:
    - sds-build
  image: sds-docker.artifactory.ci.csc.fi/sds/sdd-common-ci:1659d8af0e3757081843f2a191cd804de97e94e4
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      allow_failure: true
  script:
    - gunzip -c image.tar.gz | docker load
    - jf config import "${JF_CONFIG}"
    - |
      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
        export IMAGE_TAG="$(echo ${ENVIRONMENT:-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} | tr '/' '-')"
      elif [ "$CI_COMMIT_TAG" ]; then
        export IMAGE_TAG="$CI_COMMIT_TAG"
      else
        export IMAGE_TAG="$CI_DEFAULT_BRANCH"
      fi
    - jf docker scan --licenses --extended-table --min-severity=Medium $ARTIFACTORY_SERVER/sds/sd-submit-api:${IMAGE_TAG}

1-upload-image:
  stage: upload
  needs:
    - job: 1-build-image
      artifacts: true
    - job: 2-scan-image
  tags:
    - sds-upload
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      allow_failure: true
  before_script:
    - echo "$ARTIFACTORY_USER_PASSWORD" | docker login --username "$ARTIFACTORY_USER" --password-stdin "$ARTIFACTORY_SERVER"
  script:
    - gunzip -c image.tar.gz | docker load
    # Push to Artifactory with the same tag as built in the 1-build-image job
    - |
      if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
        export IMAGE_TAG="$(echo ${ENVIRONMENT:-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} | tr '/' '-')"
      elif [ "$CI_COMMIT_TAG" ]; then
        export IMAGE_TAG="$CI_COMMIT_TAG"
      else
        export IMAGE_TAG="$CI_DEFAULT_BRANCH"
      fi
    - echo "Pushing image sd-submit-api:${IMAGE_TAG}"
    - |
      max_retries=150
      retry=1

      until docker push "$ARTIFACTORY_SERVER/sds/sd-submit-api:${IMAGE_TAG}" ; do
        if [ "$retry" -ge "$max_retries" ]; then
           echo "docker push failed after $max_retries attempts"
           exit 1
        fi

        echo "Attempt $retry failed, retrying in 10 seconds..."
        retry=$((retry + 1))
        sleep 10
      done
    - |
      # We want to only push images to github on release.
      if [ -n "$CI_COMMIT_TAG" ]; then
        echo "This is a release (tag: $CI_COMMIT_TAG)"

        # Login to GitHub Container Registry
        echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin

        # Tag the image for GHCR
        docker tag $ARTIFACTORY_SERVER/sds/sd-submit-api:${IMAGE_TAG} ghcr.io/cscfi/metadata-submitter:latest
        docker tag $ARTIFACTORY_SERVER/sds/sd-submit-api:${IMAGE_TAG} ghcr.io/cscfi/metadata-submitter:$CI_COMMIT_SHA
        docker tag $ARTIFACTORY_SERVER/sds/sd-submit-api:${IMAGE_TAG} ghcr.io/cscfi/metadata-submitter:$CI_COMMIT_TAG

        # Push to GHCR
        echo "Pushing images ghcr.io/cscfi/metadata-submitter:latest"
        docker push ghcr.io/cscfi/metadata-submitter:latest
        echo "Pushing image ghcr.io/cscfi/metadata-submitter:$CI_COMMIT_SHA"
        docker push ghcr.io/cscfi/metadata-submitter:$CI_COMMIT_SHA
        echo "Pushing image ghcr.io/cscfi/metadata-submitter:$CI_COMMIT_TAG"
        docker push ghcr.io/cscfi/metadata-submitter:$CI_COMMIT_TAG
      fi

release-job:
  extends: .automated-release
  release:
    description: $(cat release_changes.md)

# This is a manual dry-run for developers to run in the merge request
update-versions-dryrun:
  extends: .update-versions-dryrun
  variables:
    UPDATE_VERSION_FILES_LIST: "docs/conf.py;metadata_backend/__init__.py"

# This job updates the versions
update-versions:
  extends: .update-versions
  variables:
    UPDATE_VERSION_FILES_LIST: "docs/conf.py;metadata_backend/__init__.py"
