language: python

install: pip install tox

script: tox

stages:
  - name: tests
    if: type IN (push, pull_request)

jobs:
  include:
    - stage: tests
      name: "Type hints check"
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox -e mypy
    - stage: tests
      name: "Code style check"
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox -e flake8
    - stage: tests
      name: "Isort check"
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox -e isort
    - stage: tests
      name: "Unit Tests Python 3.6"
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox -e py36
    - stage: tests
      name: "Unit Tests Python 3.7"
      python: 3.7
      before_script:
        - pip install tox-travis
      script: tox -e py37
    - stage: tests
      name: "Documentation Tests"
      python: 3.6
      before_script:
        - pip install tox-travis
      script:
        - tox -e docs

notifications:
  email: false
