services:
  backend:
    build:
      dockerfile: ./dockerfiles/Dockerfile-dev
      context: .
      target: develop
    image: cscfi/metadata-submitter-dev
    container_name: "metadata_submitter_backend_dev"
    volumes:
      - ./config:/tls
    ports:
      - "5430:5430"
    depends_on:
      - mockauth
      - mockdatacite
      - mockmetax
      - mockpid
      - mockldap
      - mock-s3
    restart: on-failure
    environment:
      - "AAI_CLIENT_SECRET=${AAI_CLIENT_SECRET}"
      - "AAI_CLIENT_ID=${AAI_CLIENT_ID}"
      - "OIDC_URL=${OIDC_URL}"
      - "OIDC_URL_TEST=${OIDC_URL_TEST}"
      - "OIDC_SECURE_COOKIE=${OIDC_SECURE_COOKIE}"
      - "BASE_URL=${BASE_URL}"
      - "REDIRECT_URL=${REDIRECT_URL}"
      - "LOG_LEVEL=${LOG_LEVEL}"
      - "DATACITE_API=${DATACITE_API}"
      - "DATACITE_PREFIX=${DATACITE_PREFIX}"
      - "DATACITE_USER=${DATACITE_USER}"
      - "DATACITE_KEY=${DATACITE_KEY}"
      - "PID_URL=${PID_URL}"
      - "PID_APIKEY=${PID_APIKEY}"
      - "METAX_DISCOVERY_URL=${METAX_DISCOVERY_URL}"
      - "BEACON_DISCOVERY_URL=${BEACON_DISCOVERY_URL}"
      - "METAX_ENABLED=${METAX_ENABLED}"
      - "METAX_USER=${METAX_USER}"
      - "METAX_PASS=${METAX_PASS}"
      - "METAX_URL=${METAX_URL}"
      - "REMS_USER_ID=${REMS_USER_ID}"
      - "REMS_KEY=${REMS_KEY}"
      - "REMS_URL=${REMS_URL}"
      - "CSC_LDAP_HOST=${CSC_LDAP_HOST}"
      - "CSC_LDAP_USER=${CSC_LDAP_USER}"
      - "CSC_LDAP_PASSWORD=${CSC_LDAP_PASSWORD}"
      - "JWT_SECRET=${JWT_SECRET}"
      - "PG_DATABASE_URL=${PG_DATABASE_URL}"
      - "BP_CENTER_ID=${BP_CENTER_ID}"
      - "POLLING_INTERVAL=${POLLING_INTERVAL}"
      - "S3_ACCESS_KEY=${S3_ACCESS_KEY}"
      - "S3_SECRET_KEY=${S3_SECRET_KEY}"
      - "S3_REGION=${S3_REGION}"
      - "S3_ENDPOINT=${S3_ENDPOINT}"
  mockauth:
    build:
      dockerfile: ./dockerfiles/Dockerfile-dev
      context: .
      target: develop
    image: cscfi/metadata-submitter-dev
    environment:
      - "LOG_LEVEL=${LOG_LEVEL}"
      - "OIDC_URL=${OIDC_URL}"
      - "OIDC_URL_TEST=${OIDC_URL_TEST}"
    hostname: mockauth
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./tests/integration/mock_auth.py:/mock_auth.py
    entrypoint: [ "python", "/mock_auth.py", "0.0.0.0", "8000" ]
  mockdatacite:
    build:
      dockerfile: ./dockerfiles/Dockerfile-dev
      context: .
      target: develop
    image: cscfi/metadata-submitter-dev
    hostname: mockdatacite
    expose:
      - 8001
    ports:
      - "8001:8001"
    volumes:
      - ./tests/integration/mock_datacite_api.py:/mock_datacite_api.py
    entrypoint: [ "python", "/mock_datacite_api.py", "0.0.0.0", "8001" ]
  mockmetax:
    build:
      dockerfile: ./dockerfiles/Dockerfile-dev
      context: .
      target: develop
    image: cscfi/metadata-submitter-dev
    hostname: mockmetax
    expose:
      - 8002
    ports:
      - "8002:8002"
    volumes:
      - ./tests/integration/mock_metax_api.py:/mock_metax_api.py
    entrypoint: [ "python", "/mock_metax_api.py", "0.0.0.0", "8002" ]
  mockrems:
    build:
      dockerfile: ./dockerfiles/Dockerfile-dev
      context: .
      target: develop
    image: cscfi/metadata-submitter-dev
    hostname: mockrems
    expose:
      - 8003
    ports:
      - "8003:8003"
    volumes:
      - ./tests/integration/mock_rems_api.py:/mock_rems_api.py
    entrypoint: [ "python", "/mock_rems_api.py", "0.0.0.0", "8003" ]
  mockadmin:
    build:
      dockerfile: dockerfiles/Dockerfile-dev
      context: .
      target: develop
    image: cscfi/metadata-submitter-dev
    environment:
      - "LOG_LEVEL=${LOG_LEVEL}"
      - "OIDC_URL_TEST=${OIDC_URL}"
    hostname: mockadmin
    expose:
      - 8004
    ports:
      - "8004:8004"
    volumes:
      - ./tests/integration/mock_admin_api.py:/mock_admin_api.py
    entrypoint: [ "python", "/mock_admin_api.py", "0.0.0.0", "8004" ]
    depends_on:
      mockauth:
        condition: service_started
  mockpid:
    build:
      dockerfile: ./dockerfiles/Dockerfile-dev
      context: .
      target: develop
    image: cscfi/metadata-submitter-dev
    hostname: mockpid
    expose:
      - 8005
    ports:
      - "8005:8005"
    entrypoint: [ "python", "/mock_pid_api.py", "0.0.0.0", "8005" ]
  mockldap:
    build:
      dockerfile: dockerfiles/Dockerfile-ldap-dev
      context: .
    image: cscfi/mockldap
    hostname: mockldap
    expose:
      - 389
    ports:
      - "389:389"
  mock-s3:
    image: motoserver/moto:latest
    hostname: s3mock
    ports:
      - "8006:8006"
    environment:
      - MOTO_PORT=8006
volumes:
  data:
