#=======================
FROM python:3.11-slim-bullseye as appbase
#=======================

RUN apt-get update \
    && apt-get install -y ca-certificates git

WORKDIR /usr/src/app

RUN pip install --upgrade pip

COPY pyproject.toml .
COPY README.md .
COPY requirements.txt .
COPY metadata_backend/ ./metadata_backend
COPY scripts ./scripts

RUN pip install authlib requests  # required for mockauth (integration test)
RUN pip install .
EXPOSE 5430

#=======================
FROM appbase as develop
#=======================

CMD ["metadata_submitter"]

#=======================
FROM appbase as local
#=======================

COPY requirements-dev.txt requirements.txt

RUN pip install --no-cache-dir

ENV PYTHONUNBUFFERED=1
