version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile-dev
      context: .
    image: cscfi/metadata-submitter-dev
    container_name: "metadata_submitter_backend_dev"
    volumes:
      - ./config:/tls
    ports:
      - 5430:5430
    depends_on:
      - database
      - mockauth
      - mockdoi
    restart: on-failure
    environment:
      - "MONGO_HOST=${MONGO_HOST}"
      - "MONGO_SSL=${MONGO_SSL}"
      - "MONGO_SSL_CA=${MONGO_SSL_CA}"
      - "MONGO_SSL_CLIENT_KEY=${MONGO_SSL_CLIENT_KEY}"
      - "MONGO_SSL_CLIENT_CERT=${MONGO_SSL_CLIENT_CERT}"
      - "AAI_CLIENT_SECRET=${AAI_CLIENT_SECRET}"
      - "AAI_CLIENT_ID=${AAI_CLIENT_ID}"
      - "OIDC_URL=${OIDC_URL}"
      - "OIDC_URL_TEST=${OIDC_URL_TEST}"
      - "BASE_URL=${BASE_URL}"
      - "REDIRECT_URL=${REDIRECT_URL}"
      - "LOG_LEVEL=${LOG_LEVEL}"
      - "MONGO_DATABASE=${MONGO_DATABASE}"
      - "MONGO_AUTHDB=${MONGO_AUTHDB}"
      - "DOI_API=${DOI_API}"
      - "DOI_PREFIX=${DOI_PREFIX}"
      - "DOI_USER=${DOI_USER}"
      - "DOI_KEY=${DOI_KEY}"
      - "METAX_USER=${METAX_USER}"
      - "METAX_PASS=${METAX_PASS}"
      - "METAX_URL=${METAX_URL}"
  database:
    image: "mongo"
    container_name: "metadata_submitter_database_dev"
    command: "mongod --tlsMode=requireTLS --tlsCertificateKeyFile=/tls/combined2 --tlsCAFile=/tls/cacert"
    restart: on-failure
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - data:/data/db
      - ./config:/tls
      - ./scripts/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro
    expose:
      - 27017
    ports:
      - 27017:27017
  mockauth:
    build:
      dockerfile: Dockerfile-dev
      context: .
    image: cscfi/metadata-submitter-dev
    environment:
      - "LOG_LEVEL=${LOG_LEVEL}"
      - "OIDC_URL=${OIDC_URL}"
      - "OIDC_URL_TEST=${OIDC_URL_TEST}"
    hostname: mockauth
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./tests/integration/mock_auth.py:/mock_auth.py
    entrypoint: ["python", "/mock_auth.py", "0.0.0.0", "8000"]
  mockdoi:
    build:
      dockerfile: Dockerfile-dev
      context: .
    image: cscfi/metadata-submitter-dev
    hostname: mockdoi
    expose:
      - 8001
    ports:
      - 8001:8001
    volumes:
      - ./tests/integration/mock_doi_api.py:/mock_doi_api.py
    entrypoint: ["python", "/mock_doi_api.py", "0.0.0.0", "8001"]
  mockmetax:
    build:
      dockerfile: Dockerfile-dev
      context: .
    image: cscfi/metadata-submitter-dev
    hostname: mockmetax
    expose:
      - 8002
    ports:
      - 8002:8002
    volumes:
      - ./tests/integration/mock_metax_api.py:/mock_metax_api.py
    entrypoint: ["python", "/mock_metax_api.py", "0.0.0.0", "8002"]
volumes:
  data: 
