# We use this image in ci so the packages don't have to be installed on each run
# and we can run both frontend and backend with it

FROM python:3.11-slim-bullseye

ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive

RUN \
      apt-get update \
      && apt-get upgrade -yqq -o Dpkg::Options::="--force-confold" \
      && apt-get install -yqq \
      # for adding a repository
      apt-transport-https \
      ca-certificates \
      gnupg-agent \
      curl \
      && apt-get install -yqq aspell aspell-en libaspell-dev \
      && apt-get update -yqq \
      && apt-get install -yqq --no-install-recommends \
      git \
      && python3 -m pip install --no-cache --upgrade pip \
      && rm -rf /var/lib/apt/lists/*

# Install Node.js and npm for frontend purposes
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -yqq nodejs

RUN python3 -m venv /venv && . /venv/bin/activate
