#=======================
FROM cscfi/python:3.8-slim-git as appbase
#=======================

RUN apt-get install ca-certificates

WORKDIR /usr/src/app

RUN pip install --upgrade pip

COPY ./setup.py .
COPY requirements.txt .
COPY metadata_backend/ ./metadata_backend

RUN pip install .

EXPOSE 5430

#=======================
FROM appbase as develop
#=======================

CMD ["metadata_submitter"]

#=======================
FROM appbase as local
#=======================

COPY requirements-dev.txt .
COPY ./scripts/ ./scripts

RUN pip install -r requirements-dev.txt 
RUN ./scripts/install-hooks.sh

ENV PYTHONUNBUFFERED=1
