matrix:
- name: Markdown
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - .github/config/.wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: '\\[\\`~]'
      delimiters:
      # Ignore text between inline back ticks as this is code or hightlight words
      - open: '(?P<open>`+)'
        close: '(?P=open)'
      # Ignore surrounded in <> as in RST it is link
      - open: '<(https?://[^\\s/$.?#].[^\\s]+|[A-Za-z0-9-_:.]+)'
        close: '>'
  sources:
  - 'docs/*.rst'
  - '**/*.md'
  default_encoding: utf-8

- name: JSON schemas
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - .github/config/.wordlist.txt
  pipeline:
  - pyspelling.filters.javascript:
      jsdocs: true
      line_comments: false
      block_comments: false
      strings: true
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: '\\[\\`~]'
      delimiters:
      # Ignore Pāli word as it cannot be added to dictionary
      - open: '(Pāli)'
        close: '-'
  sources:
  - metadata_backend/helpers/schemas/*.json
  default_encoding: utf-8
