FROM osixia/openldap:1.5.0

# https://github.com/osixia/docker-openldap

ENV LDAP_ORGANISATION="Test Org" \
    LDAP_DOMAIN="csc.fi" \
    LDAP_ADMIN_PASSWORD=admin \
    LDAP_SEED_INTERNAL_LDIF_PATH=/config/ldif \
    LDAP_SEED_INTERNAL_SCHEMA_PATH=/config/schema

# Create the schema.

RUN mkdir -p /config/schema

RUN cat <<'EOF' > /config/schema/custom.ldif
dn: cn=custom,cn=schema,cn=config
objectClass: olcSchemaConfig
cn: custom
olcAttributeTypes: ( 1.3.6.1.4.1.99999.1.1 NAME 'CSCPrjNum' DESC 'CSC Project Number' EQUALITY caseIgnoreMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
olcAttributeTypes: ( 1.3.6.1.4.1.99999.1.2 NAME 'CSCUserName' DESC 'CSC User Name' EQUALITY caseIgnoreMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
olcAttributeTypes: ( 1.3.6.1.4.1.99999.1.3 NAME 'CSCSPCommonStatus' DESC 'Common Status' EQUALITY caseIgnoreMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
olcObjectClasses: ( 1.3.6.1.4.1.99999.2.2 NAME 'cscServiceProfile' DESC 'CSC Service Profile' SUP applicationProcess STRUCTURAL MAY ( CSCUserName $ CSCPrjNum $ CSCSPCommonStatus ) )
EOF

# Create the test entries.

RUN mkdir -p /config/ldif

RUN cat <<'EOF' > /config/ldif/entries.ldif
dn: ou=idm,dc=csc,dc=fi
objectClass: organizationalUnit
ou: idm

dn: ou=SP_SD-SUBMIT,ou=idm,dc=csc,dc=fi
objectClass: organizationalUnit
ou: SP_SD-SUBMIT

dn: cn=1,ou=SP_SD-SUBMIT,ou=idm,dc=csc,dc=fi
objectClass: cscServiceProfile
cn: 1
CSCUserName: admin_user@test.what
CSCSPCommonStatus: ready
CSCPrjNum: 1000
CSCPrjNum: 2000
CSCPrjNum: 3000

dn: cn=2,ou=SP_SD-SUBMIT,ou=idm,dc=csc,dc=fi
objectClass: cscServiceProfile
cn: 2
CSCUserName: mock_user@test.what
CSCSPCommonStatus: ready
CSCPrjNum: 1000
CSCPrjNum: 2000
CSCPrjNum: 3000

dn: cn=3,ou=SP_SD-SUBMIT,ou=idm,dc=csc,dc=fi
objectClass: cscServiceProfile
cn: 3
CSCUserName: user_given@test.what
CSCSPCommonStatus: ready
CSCPrjNum: 1000
CSCPrjNum: 2000
CSCPrjNum: 3000
EOF

# Validate the LDAP schema, entries and search.
#
# - Start LDAP server:
# docker run --rm -p 389:389 --name openldap -e LDAP_ORGANISATION="CSC FI" -e LDAP_DOMAIN="csc.fi"  -e LDAP_ADMIN_PASSWORD="admin osixia/openldap:1.5.0
#
# - Check that the LDAP server is running:
# ldapsearch -H ldap://127.0.0.1 -x -b "" -s base
#
# - Check that the schema is valid:
# docker cp schema.ldif openldap:/schema.ldif
# docker exec -it openldap ldapadd -Y EXTERNAL -H ldapi:/// -f /schema.ldif
#
# - Check that the entries are valid:
# docker cp entries.ldif openldap:/entries.ldif
# docker exec -it openldap ldapadd -Y EXTERNAL -H ldapi:/// -f /entries.ldif
#
# - Check that the user projects query works:
# ldapsearch -x -H ldap://localhost:389 \
#  -D "cn=admin,dc=csc,dc=fi" \
#  -w admin \
#  -b "ou=idm,dc=csc,dc=fi" \
#  "(&(objectClass=applicationProcess)(CSCSPCommonStatus=ready)(CSCUserName=TODO_USER_NAME))" \
#  CSCPrjNum

# Build and run this container interactively.
#
# docker build -t mockldap:dev -f dockerfiles/Dockerfile-ldap-dev .
# docker run --rm -it --name mockldap -p 389:389 -p 636:636 mockldap:dev
