#=======================
FROM  node:22-trixie-slim AS build-frontend
#=======================

RUN apt update && apt -y install git

ARG BRANCH=main

RUN git clone -b ${BRANCH} https://github.com/CSCfi/metadata-submitter-frontend.git

WORKDIR /metadata-submitter-frontend

RUN npm install -g pnpm

RUN pnpm install --prod --ignore-scripts && pnpm add -D vite-plugin-node-polyfills

RUN pnpm run build

#=======================
FROM ghcr.io/astral-sh/uv:python3.14-trixie AS build-backend
#=======================

WORKDIR /app

# Copy uv files
COPY pyproject.toml .
COPY uv.lock .
COPY .python-version .

# Copy project files
COPY README.md .
COPY metadata_backend ./metadata_backend
COPY scripts ./scripts
COPY docs/openapi.yml ./docs/openapi.yml
COPY --from=BUILD-FRONTEND /metadata-submitter-frontend/build \
    ./metadata_backend/frontend

# Install dependencies and create virtual environment
RUN uv sync

# Generate OpenAPI docs.
RUN uv run scripts/swagger/generate.sh

#=======================
FROM python:3.13-slim-trixie
#=======================

LABEL maintainer="CSC Developers"
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.vcs-url="https://github.com/CSCfi/metadata-submitter"

WORKDIR /app

COPY --from=BUILD-BACKEND /app .
COPY ./deploy/app.sh .
RUN chmod +x /app/app.sh

# https://manpages.debian.org/trixie/adduser/adduser.8.en.html
RUN adduser submitter

ENV PATH="/app/uv:$PATH"
USER submitter
ENTRYPOINT ["uv", "run", "/app/app.sh"]
