FROM osixia/openldap:1.5.0

# https://github.com/osixia/docker-openldap

ENV LDAP_ORGANISATION="Test Org" \
    LDAP_DOMAIN="csc.fi" \
    LDAP_ADMIN_PASSWORD=admin \
    LDAP_SEED_INTERNAL_LDIF_PATH=/config/ldif \
    LDAP_SEED_INTERNAL_SCHEMA_PATH=/config/schema

# Create source and destination directories for schema
RUN mkdir -p /config/schema \
    && mkdir -p /container/service/slapd/assets/config/bootstrap/schema/custom

# Custom schema
RUN cat <<'EOF' > /config/schema/custom.ldif
dn: cn=custom,cn=schema,cn=config
objectClass: olcSchemaConfig
cn: custom
olcAttributeTypes: ( 1.3.6.1.4.1.99999.1.1 NAME 'CSCPrjNum' DESC 'CSC Project Number' EQUALITY caseIgnoreMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
olcAttributeTypes: ( 1.3.6.1.4.1.99999.1.2 NAME 'CSCUserName' DESC 'CSC User Name' EQUALITY caseIgnoreMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
olcAttributeTypes: ( 1.3.6.1.4.1.99999.1.3 NAME 'CSCSPCommonStatus' DESC 'Common Status' EQUALITY caseIgnoreMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
olcObjectClasses: ( 1.3.6.1.4.1.99999.2.2 NAME 'cscServiceProfile' DESC 'CSC Service Profile' SUP applicationProcess STRUCTURAL MAY ( CSCUserName $ CSCPrjNum $ CSCSPCommonStatus ) )
EOF

# Create test entries
RUN mkdir -p /config/ldif

RUN cat <<'EOF' > /config/ldif/entries.ldif
dn: ou=idm,dc=csc,dc=fi
objectClass: organizationalUnit
ou: idm

dn: ou=SP_SD-SUBMIT,ou=idm,dc=csc,dc=fi
objectClass: organizationalUnit
ou: SP_SD-SUBMIT

dn: cn=1,ou=SP_SD-SUBMIT,ou=idm,dc=csc,dc=fi
objectClass: cscServiceProfile
cn: 1
CSCUserName: admin_user@test.what
CSCSPCommonStatus: ready
CSCPrjNum: 1000
CSCPrjNum: 2000
CSCPrjNum: 3000

dn: cn=2,ou=SP_SD-SUBMIT,ou=idm,dc=csc,dc=fi
objectClass: cscServiceProfile
cn: 2
CSCUserName: mock_user@test.what
CSCSPCommonStatus: ready
CSCPrjNum: 1000
CSCPrjNum: 2000
CSCPrjNum: 3000

dn: cn=3,ou=SP_SD-SUBMIT,ou=idm,dc=csc,dc=fi
objectClass: cscServiceProfile
cn: 3
CSCUserName: user_given@test.what
CSCSPCommonStatus: ready
CSCPrjNum: 1000
CSCPrjNum: 2000
CSCPrjNum: 3000
EOF
