# https://github.com/Huachao/vscode-restclient
# https://jsonpath.com/

# To test these API calls, run all following commands in project root.

# Get secrets from Vault for local deployment:
$ make get_env_demo

# Add the JWT public key to the .env file in this way:
# JWT_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----...[rest of the key]...-----END PUBLIC KEY-----

# Run this to launch the API service locally:
$ docker compose --profile demo up --build -d

# Login at: https://login.bp.nbis.se
# Copy the uploading access token for and paste it in the variable below
@bearer_token = ...

@api_url = http://localhost:5431/api

@user_id = {{user_data_req.response.body.user_id}}

### Get user data
# @name user_data_req
curl {{api_url}}/v1/users
     -H 'Authorization: Bearer {{bearer_token}}'

### List all submissions
curl {{api_url}}/v1/submissions?projectId={{user_id}}
     -H 'Authorization: Bearer {{bearer_token}}'


# Process Bigpicture submission

### Create new submission (copy-paste to terminal because -F flags are not supported in REST Client extension)
curl -X POST '{{api_url}}/v1/submit' \
     -H 'Authorization: Bearer {{bearer_token}}' \
     -F "annotation=@./tests/test_files/xml/bigpicture/annotation.xml;type=text/xml" \
     -F "datacite=@./tests/test_files/xml/bigpicture/datacite.xml;type=text/xml" \
     -F "dataset=@./tests/test_files/xml/bigpicture/dataset.xml;type=text/xml" \
     -F "image=@./tests/test_files/xml/bigpicture/image.xml;type=text/xml" \
     -F "landing_page=@./tests/test_files/xml/bigpicture/landing_page.xml;type=text/xml" \
     -F "observation=@./tests/test_files/xml/bigpicture/observation.xml;type=text/xml" \
     -F "observer=@./tests/test_files/xml/bigpicture/observer.xml;type=text/xml" \
     -F "organisation=@./tests/test_files/xml/bigpicture/organisation.xml;type=text/xml" \
     -F "policy=@./tests/test_files/xml/bigpicture/policy.xml;type=text/xml" \
     -F "bprems=@./tests/test_files/xml/bigpicture/rems.xml;type=text/xml" \
     -F "sample=@./tests/test_files/xml/bigpicture/sample.xml;type=text/xml" \
     -F "staining=@./tests/test_files/xml/bigpicture/staining.xml;type=text/xml" | jq

# Fill in submission_id here:
@submission_id = ...

### Get submission by ID
curl {{api_url}}/v1/submissions/{{submission_id}}
     -H 'Authorization: Bearer {{bearer_token}}'

### List files in the submission
curl {{api_url}}/v1/submissions/{{submission_id}}/files
     -H 'Authorization: Bearer {{bearer_token}}'

### List metadata objects in the submission
curl {{api_url}}/v1/submissions/{{submission_id}}/objects
     -H 'Authorization: Bearer {{bearer_token}}'

### Get dataset xml file in the submission
curl {{api_url}}/v1/submissions/{{submission_id}}/objects/docs?schemaType=dataset
     -H 'Authorization: Bearer {{bearer_token}}'

### Get image xml file in the submission
curl {{api_url}}/v1/submissions/{{submission_id}}/objects/docs?schemaType=image
     -H 'Authorization: Bearer {{bearer_token}}'

### Update image xml file in the submission
curl -X PATCH {{api_url}}/v1/submit/{{submission_id}} \
     -H 'Authorization: Bearer {{bearer_token}}' \
     -F "annotation=@./tests/test_files/xml/bigpicture/annotation.xml;type=text/xml" \
     -F "datacite=@./tests/test_files/xml/bigpicture/datacite.xml;type=text/xml" \
     -F "dataset=@./tests/test_files/xml/bigpicture/dataset.xml;type=text/xml" \
     -F "image=@./tests/test_files/xml/bigpicture/update/image.xml;type=text/xml" \
     -F "landing_page=@./tests/test_files/xml/bigpicture/landing_page.xml;type=text/xml" \
     -F "observation=@./tests/test_files/xml/bigpicture/observation.xml;type=text/xml" \
     -F "observer=@./tests/test_files/xml/bigpicture/observer.xml;type=text/xml" \
     -F "organisation=@./tests/test_files/xml/bigpicture/organisation.xml;type=text/xml" \
     -F "policy=@./tests/test_files/xml/bigpicture/policy.xml;type=text/xml" \
     -F "bprems=@./tests/test_files/xml/bigpicture/rems.xml;type=text/xml" \
     -F "sample=@./tests/test_files/xml/bigpicture/sample.xml;type=text/xml" \
     -F "staining=@./tests/test_files/xml/bigpicture/staining.xml;type=text/xml" | jq

### Delete submission
curl -X DELETE {{api_url}}/v1/submit/{{submission_id}} \
     -H 'Authorization: Bearer {{bearer_token}}'
