# https://github.com/Huachao/vscode-restclient
# https://jsonpath.com/


@backend_url = http://localhost:5430
@auth_url = http://localhost:8000
@doi_url = http://localhost:8001
@metax_url = http://localhost:8002

@auth_email = mock_user@test.what


@project_id = {{user_data_req.response.body.projects[0].projectId}}
@submission_id = {{submission_id_req.response.body.submissionId}}
@study_id = {{study_id_req.response.body.accessionId}}
@dataset_id = {{dataset_id_req.response.body.accessionId}}

### Mock authentication
GET {{auth_url}}/setmock
    ?sub={{auth_email}}
    &given=Mock
    &family=Family

###
GET {{backend_url}}/aai

###
GET {{backend_url}}/logout


### Get user data
# @name user_data_req
GET {{backend_url}}/v1/users/current



### Create submission
# @name submission_id_req
POST {{backend_url}}/v1/submit
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="SUBMISSION"; value="ERA521986_valid.xml"
Content-Type: text/xml

< ../test_files/submission/ERA521986_valid.xml
------WebKitFormBoundary7MA4YWxkTrZu0gW--
Content-Disposition: form-data; name="STUDY"; value="SRP000539.xml"
Content-Type: text/xml

< ../test_files/study/SRP000539.xml
------WebKitFormBoundary7MA4YWxkTrZu0gW--
Content-Disposition: form-data; name="SAMPLE"; value="SRS001433.xml"
Content-Type: text/xml

< ../test_files/sample/SRS001433.xml
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### List submissions
GET {{backend_url}}/v1/submissions
    ?projectId={{project_id}}

### Get submission
GET {{backend_url}}/v1/submissions/{{submission_id}}

### Add XML dataset to submission
# @name study_id_req
POST {{backend_url}}/v1/objects/dataset
    ?submission={{submission_id}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="DATASET"; value="dataset.xml"
Content-Type: text/xml

< ../test_files/dataset/dataset.xml

### Get study
GET {{backend_url}}/v1/objects/study/{{study_id}}

### Update DOI in submission
PUT {{backend_url}}/v1/submissions/{{submission_id}}/doi
Content-Type: text/json

< ../test_files/doi/test_doi.json

### Update DAC in submission
PUT {{backend_url}}/v1/submissions/{{submission_id}}/dac
Content-Type: text/json

< ../test_files/dac/dac_rems.json

### Publish submission
PATCH {{backend_url}}/v1/publish/{{submission_id}}
