# https://github.com/Huachao/vscode-restclient
# https://jsonpath.com/


@backend_url = http://localhost:5430
@auth_url = http://localhost:8000
@doi_url = http://localhost:8001
@metax_url = http://localhost:8002

@auth_email = mock_user@test.what


@project_id = {{user_data_req.response.body.projects[0].projectId}}
@folder_id = {{folder_id_req.response.body.folderId}}

### Mock athentication
GET {{auth_url}}/setmock
    ?sub={{auth_email}}
    &given=Mock
    &family=Family

###
GET {{backend_url}}/aai

### Get user data
# @name user_data_req
GET {{backend_url}}/users/current



### Create folder
# @name folder_id_req
POST {{backend_url}}/folders

{
    "name": "folder test 1",
    "description": "folder test 1",
    "projectId": "{{project_id}}"
}

### List folders
GET {{backend_url}}/folders
    ?projectId={{project_id}}

### Get folder
GET {{backend_url}}/folders/{{folder_id}}

### Add study to folder
POST {{backend_url}}/objects/study
    ?folder={{folder_id}}

< ../test_files/study/SRP000539.json

### Add DOI to folder
PUT {{backend_url}}/folders/{{folder_id}}/doi

< ../test_files/doi/test_doi.json

### Publish folder
PATCH {{backend_url}}/publish/{{folder_id}}
