# https://github.com/Huachao/vscode-restclient
# https://jsonpath.com/


@backend_url = http://localhost:5430
@auth_url = http://localhost:8000
@doi_url = http://localhost:8001
@metax_url = http://localhost:8002

@auth_email = mock_user@test.what


@project_id = {{user_data_req.response.body.projects[0].projectId}}
@submission_id = {{submission_id_req.response.body.submissionId}}
@study_id = {{study_id_req.response.body.accessionId}}


### Get user data
# @name user_data_req
GET {{backend_url}}/v1/users/current



### Create submission
# @name submission_id_req
POST {{backend_url}}/v1/submissions

{
    "name": "submission test 1",
    "description": "submission test 1",
    "projectId": "{{project_id}}"
}

### Add study to submission
# @name study_id_req
POST {{backend_url}}/v1/objects/study
    ?submission={{submission_id}}

< ../test_files/study/SRP000539.json
### Update DOI in submission
PUT {{backend_url}}/v1/submissions/{{submission_id}}/doi

< ../test_files/doi/test_doi.json

### Publish submission
PATCH {{backend_url}}/v1/publish/{{submission_id}}


### List submissions
GET {{backend_url}}/v1/submissions
    ?projectId={{project_id}}

### Get submission
GET {{backend_url}}/v1/submissions/{{submission_id}}

### Get study
GET {{backend_url}}/v1/objects/study/{{study_id}}
