# https://github.com/Huachao/vscode-restclient
# https://jsonpath.com/

# Run this script in project root to create XML file payloads with test files:
# source tests/http/xml-files.sh

# Run this to launch the API service locally:
# REDIRECT_URL=http://localhost:5430 docker compose --env-file tests/integration/.env.example --profile dev up --build -d

@api_url = http://localhost:5430
@auth_url = http://localhost:8000
@auth_email = mock_user@test.what

@project_id = {{user_data_req.response.body.projects[0].project_id}}
@submission_id = {{submission_id_req.response.body.submissionId}}


### Mock authentication
curl {{auth_url}}/setmock?sub={{auth_email}}&given=Mock&family=Family

###
curl {{api_url}}/login

###
curl {{api_url}}/logout

### Get user data
# @name user_data_req
curl {{api_url}}/v1/users

### Create new submission
# @name submission_id_req
curl -X POST '{{api_url}}/v1/submit/Bigpicture?projectId={{project_id}}' \
     -H 'content-type: multipart/form-data; boundary=WebKitFormBoundary' \
     --data-binary @xml-files.txt

### List all submissions
curl {{api_url}}/v1/submissions?projectId={{project_id}}

### Get submission by ID
curl {{api_url}}/v1/submissions/{{submission_id}}

### List metadata objects in the submission
curl {{api_url}}/v1/submissions/{{submission_id}}/objects

### Get dataset xml file in the submission
curl {{api_url}}/v1/submissions/{{submission_id}}/objects/docs?schemaType=dataset

### Get image xml file in the submission
curl {{api_url}}/v1/submissions/{{submission_id}}/objects/docs?schemaType=image

### Update image xml file in the submission
curl -X PATCH {{api_url}}/v1/submit/Bigpicture/{{submission_id}}?projectId={{project_id}}
     -H 'content-type: multipart/form-data; boundary=WebKitFormBoundary' \
     --data-binary @xml-files-update.txt

### Delete submission
curl -X DELETE {{api_url}}/v1/submit/Bigpicture/{{submission_id}}?projectId={{project_id}}
